# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded pkgcmd 0.0 [list source [file join $dir pkgcmd.tcl]]
package ifneeded pkgrepo 0.0 [list source [file join $dir pkgrepo.tcl]]
package ifneeded pkgtk 0.0 [list source [file join $dir main.tcl]]
package ifneeded pkgview 0.0 [list source [file join $dir pkgview.tcl]]
package ifneeded utils 0.0 [list source [file join $dir utils.tcl]]
