# $FreeBSD$

PORTNAME=		pkgtk
DISTVERSIONPREFIX=	v
DISTVERSION=		0.8
CATEGORIES=		ports-mgmt x11-toolkits

MAINTAINER=		jrmsdev@gmail.com
COMMENT=		pkgng Tcl/Tk GUI

LICENSE=		BSD3CLAUSE
LICENSE_FILE=		${WRKSRC}/LICENSE

USE_GITHUB=		yes
GH_ACCOUNT=		jrmsdev

RUN_DEPENDS=

.include <bsd.port.mk>
